export const exampleMovies = [{
    "adult": false,
    "belongs_to_collection": "Toy Story Collection",
    "budget": "30000000",
    "original_language": "en",
    "original_title": "Toy Story",
    "overview": "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
    "popularity": 21.946943,
    "release_date": "1995-10-30",
    "revenue": "373554033.0",
    "runtime": "81.0",
    "tagline": "not available",
    "title": "Toy Story",
    "vote_average": "7.7",
    "vote_count": "5415.0",
    "languages": "['English']",
    "day_of_week": "Monday",
    "month": "Oct",
    "season": "Q4",
    "year": "1995",
    "has_homepage": "YES",
    "genre": "['Animation', 'Comedy', 'Family']",
    "companies": "['Pixar Animation Studios']",
    "countries": "['United States of America']"
},
{
    "adult": false,
    "belongs_to_collection": "not available",
    "budget": "65000000",
    "original_language": "en",
    "original_title": "Jumanji",
    "overview": "When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.",
    "popularity": 17.015539,
    "release_date": "1995-12-15",
    "revenue": "262797249.0",
    "runtime": "104.0",
    "tagline": "Roll the dice and unleash the excitement!",
    "title": "Jumanji",
    "vote_average": "6.9",
    "vote_count": "2413.0",
    "languages": "['English', 'Français']",
    "day_of_week": "Friday",
    "month": "Dec",
    "season": "Q4",
    "year": "1995",
    "has_homepage": "NO",
    "genre": "['Adventure', 'Fantasy', 'Family']",
    "companies": "['TriStar Pictures', 'Teitler Film', 'Interscope Communications']",
    "countries": "['United States of America']"
},
{
    "adult": false,
    "belongs_to_collection": "Grumpy Old Men Collection",
    "budget": "0",
    "original_language": "en",
    "original_title": "Grumpier Old Men",
    "overview": "A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max.",
    "popularity": 11.7129,
    "release_date": "1995-12-22",
    "revenue": "0.0",
    "runtime": "101.0",
    "tagline": "Still Yelling. Still Fighting. Still Ready for Love.",
    "title": "Grumpier Old Men",
    "vote_average": "6.5",
    "vote_count": "92.0",
    "languages": "['English']",
    "day_of_week": "Friday",
    "month": "Dec",
    "season": "Q4",
    "year": "1995",
    "has_homepage": "NO",
    "genre": "['Romance', 'Comedy']",
    "companies": "['Warner Bros.', 'Lancaster Gate']",
    "countries": "['United States of America']"
},
{
    "adult": false,
    "belongs_to_collection": "not available",
    "budget": "16000000",
    "original_language": "en",
    "original_title": "Waiting to Exhale",
    "overview": "Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive \"good man\" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, Glo and Robin talk it all out, determined to find a better way to breathe.",
    "popularity": 3.859495,
    "release_date": "1995-12-22",
    "revenue": "81452156.0",
    "runtime": "127.0",
    "tagline": "Friends are the people who let you be yourself... and never let you forget it.",
    "title": "Waiting to Exhale",
    "vote_average": "6.1",
    "vote_count": "34.0",
    "languages": "['English']",
    "day_of_week": "Friday",
    "month": "Dec",
    "season": "Q4",
    "year": "1995",
    "has_homepage": "NO",
    "genre": "['Comedy', 'Drama', 'Romance']",
    "companies": "['Twentieth Century Fox Film Corporation']",
    "countries": "['United States of America']"
}]